# Generated by Django 6.1 on 2026-08-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='invoive',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='ceated_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='customer',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1),
        ),
    ]
